# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77ff0768608cd79d33508eb7b2f1d572"
application_url = "https://sisters-nutritional-outreach-donors.trycloudflare.com"
embedded = true
name = "reviewer-9000"
handle = "reviewer-9007"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_customers,read_metaobject_definitions,read_metaobjects,write_customers,write_metaobject_definitions,write_metaobjects,write_products,read_products"

[auth]
redirect_urls = [
  "https://sisters-nutritional-outreach-donors.trycloudflare.com/auth/callback",
  "https://sisters-nutritional-outreach-donors.trycloudflare.com/auth/shopify/callback",
  "https://sisters-nutritional-outreach-donors.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://sisters-nutritional-outreach-donors.trycloudflare.com/api/public"
subpath = "reviewer-9000"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
